collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1756629
  lightness: 0.8516374
  brandStrength: 0.5483871
  brandColors:
    - '#FCFBFB'
    - '#C6BDC6'
    - '#28222E'
    - '#995430'
    - '#AD036C'
  rhythmicContrast: 0.7113388
typography_spectrum: 0.2706093
layout_spectrum: 0.8655914
name: Excelcreditcard
