layout_spectrum: 0.4301075
color:
  saturation: 0.1756629
  brandStrength: 0
  lightness: 0.8516374
  rhythmicContrast: 0.7113388
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.2706093
name: Excelcreditcard
