collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2706093
color:
  saturation: 0.1756629
  brandStrength: 1
  rhythmicContrast: 0.7113388
  brandColors:
    - '#FBE9D0'
    - '#18140D'
    - '#5C1517'
    - '#6D6676'
    - '#AB6F5C'
  lightness: 0.8516374
layout_spectrum: 0.8655914
name: Excelcreditcard
