collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1756629
  lightness: 0.8516374
  brandStrength: 1
  brandColors:
    - '#FBE9D0'
    - '#18140D'
    - '#5C1517'
    - '#6D6676'
    - '#AB6F5C'
  rhythmicContrast: 0.7113388
typography_spectrum: 0.2706093
layout_spectrum: 0.4301075
name: Excelcreditcard
